import {test,expect} from '@playwright/test';
import {expeditionAccount} from './expedition-account-fixture';

test('shared title header, expedition card, independent audio and account entry',async({page})=>{
  test.skip(process.env.ICP_LOCAL_BACKEND!=='1','Requires the local accounts service.');
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await expeditionAccount(page,83,true);
  await page.context().route('https://id.ai/**',route=>route.fulfill({body:'Human identity gesture substituted.'}));
  page.on('popup',popup=>void popup.close());
  await page.goto('/');
  await expect(page.locator('#start')).toBeEnabled({timeout:20000});
  await expect(page.locator('.coming-next')).toHaveCount(0);
  await expect(page.getByText('Solo deliveries',{exact:true})).toHaveCount(0);
  await expect(page.locator('.track-choice')).toHaveCount(3);
  await expect(page.getByRole('link',{name:'Solo',exact:true})).toHaveAttribute('aria-current','page');
  await page.screenshot({path:'/private/tmp/updated-solo-title.png'});
  await page.getByRole('link',{name:'Co-op',exact:true}).click();
  await expect(page.locator('#exp-explore')).toBeEnabled({timeout:20000});
  await expect(page.getByRole('link',{name:'Co-op',exact:true})).toHaveAttribute('aria-current','page');
  await expect(page.locator('#exp-copy')).toHaveCount(1);
  await expect(page.locator('#exp-code')).toBeVisible();
  await page.locator('#exp-code').fill('bad-invite');await page.locator('#exp-code').press('Enter');
  await expect(page.locator('#exp-lobby-title')).toHaveText('Couldn’t connect.');await page.locator('#exp-cancel').click();
  await expect(page.locator('#exp-card')).toContainText('Forest Crossing');
  await expect(page.locator('#exp-card')).toContainText('5–10 min');
  await expect(page.locator('#exp-card')).toContainText('Moderate');
  await expect(page.locator('#exp-card')).toContainText('3 paths');
  await expect(page.locator('#exp-card canvas')).toHaveCount(0);
  await expect(page.locator('#exp-card img')).toHaveJSProperty('naturalWidth',480);
  await page.locator('#music-toggle').click();
  await expect(page.locator('#music-toggle')).toHaveAttribute('aria-pressed','false');
  await expect(page.locator('#effects-toggle')).toHaveAttribute('aria-pressed','true');
  await page.locator('#effects-toggle').click();
  await expect(page.locator('#effects-toggle')).toHaveAttribute('aria-pressed','false');
  await page.locator('#music-toggle').click();
  await expect(page.locator('#music-toggle')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#effects-toggle')).toHaveAttribute('aria-pressed','false');
  await page.evaluate(()=>sessionStorage.setItem('finish-test-cancel','yes'));
  await page.locator('#account-toggle').click();
  await expect(page.locator('#account-feedback')).toContainText('cancelled');
  await page.locator('#account-toggle').click();
  await expect(page.locator('#account-toggle')).toHaveText('Connecting…');
  await expect(page.locator('#account-panel')).toBeVisible({timeout:30000});
  const nickname=await page.locator('#nickname').inputValue();
  await expect(page.locator('#account-toggle')).toHaveText(`${nickname} ↗`);
  await page.locator('#close-account').click();
  await expect(page.locator('#exp-menu')).toBeVisible();
  await expect(page.locator('#exp-lobby')).toBeHidden();
  await page.screenshot({path:'/private/tmp/updated-expedition-title.png'});
  await page.locator('#account-toggle').click();
  await page.locator('#sign-out').click();
  await expect(page.locator('#account-toggle')).toContainText('Sign in');
  await page.locator('#close-account').click();
  await page.setViewportSize({width:390,height:844});
  for(const id of ['music-toggle','effects-toggle','account-toggle'])await expect(page.locator(`#${id}`)).toBeVisible();
  await page.screenshot({path:'/private/tmp/updated-expedition-phone.png'});
  const header=await page.locator('.masthead').boundingBox();expect(header!.x+header!.width).toBeLessThanOrEqual(390);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.getByRole('link',{name:'Solo',exact:true}).click();
  await expect(page.locator('#start')).toBeEnabled({timeout:20000});
  await page.screenshot({path:'/private/tmp/updated-solo-phone.png'});
  expect(errors).toEqual([]);
});
