import { test, expect } from '@playwright/test';
import { startPractice, state, walkTo } from './helpers';

test('local recovery shortcut, camera drag, pause freezes ticks, resume and restart', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await startPractice(page);
  expect((await state(page)).progress.enteredDitch).toBe(true);
  await page.mouse.move(650, 400);
  await page.mouse.down();
  await page.mouse.move(730, 430, { steps: 5 });
  await page.mouse.up();
  await page.getByRole('button', { name: 'Pause game' }).click();
  const tick = (await state(page)).tick;
  await page.waitForTimeout(350);
  expect((await state(page)).tick).toBe(tick);
  await page.getByRole('button', { name: 'Back to the road' }).click();
  await expect.poll(async () => (await state(page)).tick).toBeGreaterThan(tick);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Start over' }).click();
  expect((await state(page)).vehicle.position.z).toBeCloseTo(39, 0);
  expect(errors).toEqual([]);
});

test('winch shows slack and tension, survives stop/start, and exposes controls in the cab', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/');
  await startPractice(page);
  await page.waitForTimeout(800);
  await walkTo(page, 2.6, 41.8);
  await page.keyboard.press('KeyF');
  expect((await state(page)).winch.phase).toBe('carried');
  await walkTo(page, 3.5, 58);
  await page.keyboard.press('KeyE');
  await page.keyboard.down('KeyR');
  await expect.poll(async () => { const s = await state(page); return s.winch.length - s.winch.span; }, { timeout: 8000 }).toBeGreaterThan(2.2);
  await page.keyboard.up('KeyR');
  await expect(page.locator('#winch-state')).toHaveText('SLACK');
  expect((await state(page)).winch.length - (await state(page)).winch.span).toBeGreaterThan(2);
  await page.screenshot({ path: 'test-results/cable-slack.png' });
  await page.keyboard.down('KeyQ');
  await expect(page.locator('#winch-state')).toHaveText('TAUT', { timeout: 8000 });
  await expect.poll(async () => (await state(page)).vehicle.position.z, { timeout: 30000 }).toBeGreaterThan(46);
  await page.keyboard.up('KeyQ');
  const heldLength = (await state(page)).winch.length;
  await page.waitForTimeout(1500);
  expect((await state(page)).winch.length).toBeCloseTo(heldLength, 3);
  await page.screenshot({ path: 'test-results/cable-taut.png' });
  const rv = (await state(page)).vehicle.position;
  await walkTo(page, rv.x + 2.5, rv.z);
  await page.keyboard.press('KeyE');
  expect((await state(page)).player.driving).toBe(true);
  await expect(page.locator('#prompt')).toContainText('Q · Pull');
  await expect(page.locator('#controls')).toContainText('Q R');
  await page.keyboard.down('KeyQ');
  await expect.poll(async () => (await state(page)).progress.recovered, { timeout: 45000 }).toBe(true);
  await page.keyboard.up('KeyQ');
  await page.screenshot({ path: 'test-results/cable-driving.png' });
  await page.keyboard.press('KeyF');
  expect((await state(page)).winch.phase).toBe('stowed');
  expect(errors).toEqual([]);
});
